import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'

export async function POST(request: Request) {
  try {
    const supabase = createServerClient()
    const { data: { session } } = await supabase.auth.getSession()

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { name } = await request.json()

    if (!name || name.trim().length === 0) {
      return NextResponse.json({ error: 'Team name required' }, { status: 400 })
    }

    // Create team (join_code will be auto-generated by database trigger)
    const { data: team, error: teamError } = await supabase
      .from('teams')
      .insert({
        name: name.trim(),
        owner_id: session.user.id,
        song_credits_remaining: 0, // Starts with 0 credits
        total_credits_purchased: 0,
      })
      .select()
      .single()

    if (teamError) {
      console.error('Error creating team:', teamError)
      return NextResponse.json(
        { error: 'Failed to create team. Please try again.' },
        { status: 500 }
      )
    }

    // Add owner as a team member
    const { error: memberError } = await supabase
      .from('team_members')
      .insert({
        team_id: team.id,
        user_id: session.user.id,
        role: 'owner',
      })

    if (memberError) {
      console.error('Error adding owner to team:', memberError)
      // Clean up team if member creation fails
      await supabase.from('teams').delete().eq('id', team.id)
      return NextResponse.json(
        { error: 'Failed to create team. Please try again.' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      team: {
        id: team.id,
        name: team.name,
        joinCode: team.join_code,
      },
      message: `Team "${team.name}" created successfully!`,
    })
  } catch (error) {
    console.error('Create team error:', error)
    return NextResponse.json(
      { error: 'Failed to create team' },
      { status: 500 }
    )
  }
}
